apiVersion: v1
kind: Secret
metadata:
  name: hello-secrets
  namespace: hello
type: Opaque
stringData:
  POSTGRES_DB: hello_db
  POSTGRES_USER: hello_user
  POSTGRES_PASSWORD: hello_pass

  PGADMIN_EMAIL: m.gruenzweil@htl-leonding.ac.at
  PGADMIN_PASSWORD: admin123
