# Image/Ingress
quarkus.container-image.image=htl-test/k8stest:1.0.1
quarkus.kubernetes.image-pull-policy=Never
quarkus.kubernetes.ingress.expose=true
  
greeting.message.properties=Hello from application.properties
  
# ENV-Mapping from ConfigMap:
quarkus.kubernetes.env.mapping.GREETING_MESSAGE_CONFIGMAP.from-configmap=k8stest-config
quarkus.kubernetes.env.mapping.GREETING_MESSAGE_CONFIGMAP.with-key=message_configmap
  
quarkus.kubernetes.env.mapping.GREETING_MESSAGE_SECRET.from-secret=k8stest-secret
quarkus.kubernetes.env.mapping.GREETING_MESSAGE_SECRET.with-key=message_secret