quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.port=6745

# Tell Quarkus to allow connections from every other IP
# instead of just 127.0.0.1, which is default.
quarkus.http.host=0.0.0.0